### ISSUE TITLE
Bumped tested WP versions

### ISSUE THREAD

**Issue by helgatheviking** [coenjacobs/wc-bundle-style-coupons#7]
Hi Coen! I had someone asking me about this feature and wanted to recommend this plugin. But this plugin is no longer showing up in WordPress.org searches since the header info says it hasn't been updated in the past 3 major WP versions. Is this still functioning? I will try to give it a test later... if so, could we get the version numbers bumped?

**Comment by helgatheviking** [comment]
@coenjacobs well this PR is outdated now, but I had somebody who could use this today. Do you think we could get the versions bumped? Gonna test tomorrow, but as far as I know it should still work fine.

**Comment by coenjacobs** [comment]
Merged in #6.
